### ISSUE TITLE
Unable to generate Mesh using KiMesh Plugin

### ISSUE THREAD

**Issue by CHENCHETY-ABHISHEK** [jaseg/kimesh#4]
## Goal
Generate a mesh using 2 wire and 2 pin connector.
### Schematic 
![image](https://github.com/jaseg/kimesh/assets/88726684/fee039d7-744e-4eab-83de-952778bbfd01)

### PCB layout view 
![image](https://github.com/jaseg/kimesh/assets/88726684/04df5333-edde-4b86-88a3-eae9c5a961e9)

Unable to generate mesh using below mentioned steps.

**Procedure followed:**
- Installed **shapely, matplotlib, click** libraries using **KiCad 7.99 CMD prompt** in **normal mode** (i.e., not as Administrator)
1. Assign one of the two wire magic footprint to J1 conn_01x02
2. In PCB layout, update PCB components from schematic and defined Board edge in **Edge cut layer**
3. Created graphical polygon for mesh in **User.Eco1 Layer** 
4. Placed Anchor Edge at mesh outline.
5. Using updated plugin code from GitHub and selected Anchor footprint as **J1** and Click on generate

**And below is the version info of KiCad Nightly build:**
Application: KiCad x64 on x64

Version: 7.99.0-3331-g97901c9ac5, release build

Libraries:
	wxWidgets 3.2.3
	FreeType 2.12.1
	HarfBuzz 8.2.1
	FontConfig 2.14.2
	libcurl/8.4.0-DEV Schannel zlib/1.3

Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Oct 23 2023 07:18:23
	wxWidgets: 3.2.3 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.4.0-DEV
	ngspice: 41
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

**Comment by jaseg** [comment]
Two things:

1. The schematic you did does not correspond to the mesh footprint. You can exactly copy the schematic from the README, which is for a two-wire mesh. [Link](https://github.com/jaseg/kimesh/blob/main/screenshot-mesh-schematic.png)
2. J1 has to be inside the mesh area. Either move J1, or extend the mesh area to cover J1.

**Comment by CHENCHETY-ABHISHEK** [comment]
**Still unable to generate mesh, am I missing any thing else?**
- Tried with the exact copy of schematic from readme and moved footprint inside mesh area 
![image](https://github.com/jaseg/kimesh/assets/88726684/6db6935d-5151-44ef-ac0e-ae0e43a2d50b)
 
![image](https://github.com/jaseg/kimesh/assets/88726684/e664784e-f49e-45e7-ac0d-62400e5a94f5)

**Comment by jaseg** [comment]
You could try updating KiMesh, I pushed some fixes yesterday. Note that with the large mesh footprints, your mesh area would fit at most one or two mesh tiles anyway. Perhaps try a smaller mesh anchor footprint?

If you don't mind, you could post your `.kicad_pcb` file as an attachment here, and I can have a look.

**Comment by CHENCHETY-ABHISHEK** [comment]
[pcb.zip](https://github.com/jaseg/kimesh/files/13115218/pcb.zip)
PFA `.kicad_pcb` file 

Also tried with smaller footprint with updated code, still unable to generate

**Comment by jaseg** [comment]
Huh, I did get an error when running it inside an empty project. That error was because it couldn't find the settings json file. But with that error cleared, kimesh v1.0.0 does generate a mesh just fine here. What exactly happens when you run it? Can you post a screenshot of the KiMesh window open?

**Comment by CHENCHETY-ABHISHEK** [comment]
I am able to generate mesh in win11 but not on win10
### Generated Mesh on Win11:
![image](https://github.com/jaseg/kimesh/assets/88726684/a06d25fc-c387-4772-ba48-9f066a855daf)

### Error on Windows 10:
![image](https://github.com/jaseg/kimesh/assets/88726684/19d62b0e-9f8c-4227-b24b-4e62052b1b16)


I have tried in multiple win10 machines same issue has been observed.
Also tried with VirtualBox win10 image still same issue.

**Comment by jaseg** [comment]
Your second screenshot shows an error message caused by an older version of KiMesh. Update KiMesh and it will work.

**Comment by CHENCHETY-ABHISHEK** [comment]
Got it, thanks Jan
